const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
let W=1280,H=720,keys={},running=false,last=0,toastT=0,buildMode=null;
const world={w:2200,h:1400,time:0,day:1,env:72,energy:20,zero:0,won:false};
const player={x:1100,y:700,r:14,stamina:100,health:100,inv:{metal:20,wood:10,stone:0,copper:0,plates:0}};
const base={x:1100,y:700,r:115}; let nodes=[],buildings=[];
const recipes={panel:{label:'Solar Panel',cost:{plates:2,wood:5}},smelter:{label:'Smelter',cost:{metal:15,stone:10}},battery:{label:'Solar Battery',cost:{plates:2,copper:2}},purifier:{label:'Air Purifier',cost:{plates:3,wood:4}}};
function reset(){Object.assign(world,{time:0,day:1,env:72,energy:20,zero:0,won:false});Object.assign(player,{x:1100,y:700,stamina:100,health:100,inv:{metal:20,wood:10,stone:0,copper:0,plates:0}});buildings=[];nodes=[];let types=['metal','metal','metal','wood','wood','wood','stone','stone','stone','copper','copper'];for(let i=0;i<42;i++){let a=Math.random()*Math.PI*2,d=160+Math.random()*850,t=types[i%types.length];nodes.push({x:base.x+Math.cos(a)*d,y:base.y+Math.sin(a)*d,type:t,alive:true,respawn:0});}renderUI()}
function resize(){let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);W=r.width;H=r.height}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['1','2','3','4'].includes(e.key)){buildMode=['panel','smelter','battery','purifier'][+e.key-1];syncBuild()}if(e.key.toLowerCase()==='e')interact();if(e.code==='Space'){e.preventDefault();smelt()}});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{buildMode=b.dataset.build;syncBuild()});
function syncBuild(){document.querySelectorAll('[data-build]').forEach(b=>b.classList.toggle('active',b.dataset.build===buildMode));say(`${recipes[buildMode].label} selected — click terrain to place`)}
canvas.onclick=e=>{if(!running||!buildMode)return;let p=screenToWorld(e.offsetX,e.offsetY),r=recipes[buildMode];if(!afford(r.cost))return say('Insufficient processed materials');for(let k in r.cost)player.inv[k]-=r.cost[k];buildings.push({type:buildMode,x:p.x,y:p.y,charge:0,on:true,progress:0});say(`${r.label} constructed`);buildMode=null;syncBuild();renderUI()};
function afford(c){return Object.entries(c).every(([k,v])=>(player.inv[k]||0)>=v)}function daylight(){return (world.time%120)<78}function hour(){return 6+(world.time%120)/120*24}
function camera(){return{x:Math.max(0,Math.min(world.w-W,player.x-W/2)),y:Math.max(0,Math.min(world.h-H,player.y-H/2))}}function screenToWorld(x,y){let c=camera();return{x:x+c.x,y:y+c.y}}
function nearest(){let all=[...nodes.filter(n=>n.alive),...buildings];let best=null,bd=58;for(let o of all){let d=Math.hypot(o.x-player.x,o.y-player.y);if(d<bd){best=o;bd=d}}return best}
function interact(){let o=nearest();if(!o)return say('Nothing within interaction range');if(o.type==='panel'){let n=Math.floor(o.charge);if(n){world.energy+=n;o.charge=0;say(`Collected ${n} solar energy`)}else say('Panel storage is empty')}else if(['metal','wood','stone','copper'].includes(o.type)){o.alive=false;o.respawn=60;player.inv[o.type]+=o.type==='wood'?3:o.type==='stone'?4:o.type==='copper'?1:3;say(`${o.type.toUpperCase()} collected`)}else if(o.type==='battery'){o.on=!o.on;say(`Battery ${o.on?'connected':'isolated'}`)}else if(o.type==='smelter')smelt();renderUI()}
function smelt(){let s=buildings.find(b=>b.type==='smelter'&&Math.hypot(b.x-player.x,b.y-player.y)<75);if(!s)return say('Stand beside a smelter');if(s.progress)return say('Smelter batch already running');if(player.inv.metal<1||world.energy<5)return say('Requires 1 metal and 5 solar energy');player.inv.metal--;world.energy-=5;s.progress=15;s.on=true;say('Smelting metal plate — 15 seconds');renderUI()}
function update(dt){world.time+=dt;world.env-=dt*.055;let day=daylight(),panels=buildings.filter(b=>b.type==='panel');for(let b of buildings){if(b.type==='panel'&&day)b.charge=Math.min(20,b.charge+dt/6);if(b.type==='smelter'&&b.progress){b.progress-=dt;if(b.progress<=0){b.progress=0;player.inv.plates++;say('Metal plate complete')}}if(b.type==='purifier'&&world.energy>0){world.env=Math.min(100,world.env+dt*.12);world.energy=Math.max(0,world.energy-dt*.07)}}
 for(let n of nodes)if(!n.alive&&(n.respawn-=dt)<=0)n.alive=true;
 let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),len=Math.hypot(dx,dy)||1,sprint=keys.shift&&player.stamina>0;player.x=Math.max(10,Math.min(world.w-10,player.x+dx/len*(sprint?260:145)*dt));player.y=Math.max(10,Math.min(world.h-10,player.y+dy/len*(sprint?260:145)*dt));player.stamina=Math.max(0,Math.min(100,player.stamina+(sprint&&dx+dy!==0?-18:12)*dt));
 if(world.energy<=0)world.zero+=dt;else world.zero=0;if(world.env<=0||world.zero>=60)end(false);let battery=buildings.some(b=>b.type==='battery'),purifier=buildings.some(b=>b.type==='purifier');if(world.time>=180&&panels.length&&battery&&purifier&&world.env>=20)end(true);renderUI();if(toastT>0){toastT-=dt;if(toastT<=0)document.querySelector('#toast').style.opacity=0}}
function end(win){if(world.won)return;world.won=true;running=false;document.querySelector('#end').classList.remove('hidden');document.querySelector('#end-tag').textContent=win?'PROTOCOL COMPLETE':'MISSION FAILED';document.querySelector('#end-title').textContent=win?'A living grid. A second chance.':world.env<=0?'The atmosphere collapsed.':'The settlement went dark.';document.querySelector('#end-copy').textContent=win?'Your solar settlement survived three minutes and began healing the planet. Earth has a future again.':'Balance power generation, storage, and restoration to keep the settlement alive.'}
function say(t){let el=document.querySelector('#toast');el.textContent=t;el.style.opacity=1;toastT=2.5}
function renderUI(){let h=hour()%24,hh=String(Math.floor(h)).padStart(2,'0'),mm=String(Math.floor((h%1)*60)).padStart(2,'0');document.querySelector('#clock').textContent=`${daylight()?'DAYLIGHT':'NIGHT'} · ${hh}:${mm} · ${Math.max(0,180-world.time)|0}s`;document.querySelector('#stats').innerHTML=`<div><div class=label>ENVIRONMENT</div><div class=value style="color:${world.env<25?'var(--bad)':'var(--good)'}">${Math.max(0,world.env)|0}%</div></div><div><div class=label>GRID ENERGY</div><div class=value>${world.energy|0} ☀</div></div><div><div class=label>HEALTH</div><div class=value>${player.health|0}</div></div><div><div class=label>STAMINA</div><div class=value>${player.stamina|0}</div></div>`;document.querySelector('#inventory').innerHTML=Object.entries(player.inv).map(([k,v])=>`<div><span class=label>${k.toUpperCase()}</span> <span class=value>${v}</span></div>`).join('');let checks=[['Build a Smelter',buildings.some(b=>b.type==='smelter')],['Construct a Solar Panel',buildings.some(b=>b.type==='panel')],['Store power in a Battery',buildings.some(b=>b.type==='battery')],['Activate an Air Purifier',buildings.some(b=>b.type==='purifier')],['Survive until extraction',world.time>=180]];document.querySelector('#objectives').innerHTML=checks.map(x=>`<div class="obj ${x[1]?'done':''}">${x[1]?'◆':'◇'} ${x[0]}</div>`).join('')}
function draw(){let c=camera(),day=daylight();ctx.fillStyle=day?'#806637':'#111d29';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-c.x,-c.y);let g=ctx.createRadialGradient(base.x,base.y,40,base.x,base.y,900);g.addColorStop(0,day?'#8a764b':'#26384a');g.addColorStop(1,day?'#342f25':'#111820');ctx.fillStyle=g;ctx.fillRect(0,0,world.w,world.h);ctx.strokeStyle='#ffffff08';for(let x=0;x<world.w;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,world.h);ctx.stroke()}for(let y=0;y<world.h;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(world.w,y);ctx.stroke()}ctx.fillStyle='#b8d6c318';ctx.beginPath();ctx.arc(base.x,base.y,base.r,0,7);ctx.fill();ctx.strokeStyle='#55e9ff66';ctx.stroke();drawBuilding({type:'shelter',x:base.x,y:base.y});for(let n of nodes)if(n.alive)drawNode(n);for(let b of buildings)drawBuilding(b);ctx.fillStyle='#ffb522';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,7);ctx.fill();ctx.fillStyle='#16262b';ctx.fillRect(player.x-6,player.y-20,12,15);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(player.x,player.y-4);ctx.lineTo(player.x+Math.cos(world.time*3)*15,player.y+14);ctx.stroke();ctx.restore();let n=nearest(),p=document.querySelector('#prompt');if(n){p.textContent=n.type==='panel'?'E — COLLECT SOLAR CHARGE':n.type==='smelter'?'E / SPACE — SMELT METAL':['metal','wood','stone','copper'].includes(n.type)?`E — COLLECT ${n.type.toUpperCase()}`:'E — INTERACT';p.style.opacity=1}else p.style.opacity=0;if(!day){ctx.fillStyle='#07102188';ctx.fillRect(0,0,W,H)}requestAnimationFrame(draw)}
function drawNode(n){let col={metal:'#879da5',wood:'#9b6c36',stone:'#77756d',copper:'#d07c4e'}[n.type];ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(n.x,n.y+8,20,8,0,0,7);ctx.fill();ctx.fillStyle=col;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(n.x+(i-1)*10,n.y-(i%2)*8,10,0,7);ctx.fill()}ctx.fillStyle='#fff9';ctx.font='10px ui-monospace';ctx.fillText(n.type.toUpperCase(),n.x-22,n.y-25)}
function drawBuilding(b){let map={shelter:['#263b40','SHELTER'],panel:['#16677a','SOLAR'],smelter:['#7b4b2b','SMELTER'],battery:['#4a5d2b','BATTERY'],purifier:['#355c55','PURIFIER']},[col,label]=map[b.type];ctx.fillStyle='#0006';ctx.fillRect(b.x-28,b.y-16,65,46);ctx.fillStyle=col;ctx.fillRect(b.x-32,b.y-28,64,48);ctx.strokeStyle='#9eeaf277';ctx.strokeRect(b.x-32,b.y-28,64,48);if(b.type==='panel'){ctx.strokeStyle='#9befff';for(let i=-24;i<25;i+=12){ctx.beginPath();ctx.moveTo(b.x+i,b.y-25);ctx.lineTo(b.x+i,b.y+17);ctx.stroke()}}ctx.fillStyle='#eaf9f7';ctx.font='9px ui-monospace';ctx.textAlign='center';ctx.fillText(label,b.x,b.y+34);ctx.textAlign='left';if(b.progress){ctx.fillStyle='#111';ctx.fillRect(b.x-28,b.y+40,56,5);ctx.fillStyle='#ffb522';ctx.fillRect(b.x-28,b.y+40,56*(1-b.progress/15),5)}}
function loop(t){let dt=Math.min(.04,(t-last)/1000||0);last=t;if(running)update(dt);requestAnimationFrame(loop)}document.querySelector('#begin').onclick=()=>{document.querySelector('#start').classList.add('hidden');running=true;last=performance.now()};document.querySelector('#restart').onclick=()=>{document.querySelector('#end').classList.add('hidden');reset();running=true;last=performance.now()};reset();requestAnimationFrame(draw);requestAnimationFrame(loop);
